name: Build and Push Docker image to Docker Hub

on:
  push:
    branches:
      - test

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .  # Usa el contexto del repositorio actual
          file: ./Dockerfile  # Asegúrate de que la ruta sea correcta
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/graphql-image:latest
